### ISSUE TITLE
Buscar bibliotecas de IA para Golang

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#1]
Tensorflow, OpenCV para golang

**Comment by Daztery** [comment]
https://gocv.io/ Gocv es una alternativa de OpenCv ambientado al lenguage Go.

**Comment by enzoftware** [comment]
- https://github.com/Kagami/go-face
- https://github.com/Pardus-Kurumsal/go-dlib

**Comment by enzoftware** [comment]
> https://gocv.io/ Gocv es una alternativa de OpenCv ambientado al lenguage Go.

Algo relacionado a tensorflow??

**Comment by enzoftware** [comment]
https://github.com/ageitgey/face_recognition 

---

Podemos buscar el reconocimiento facial en python y consumirlo como un servicio rest con golang.

Podemos hacer profe? @pcsilcan

**Comment by enzoftware** [comment]
Empezar con #10, utilizando lo discutiod aqui
