### ISSUE TITLE
Realizar modelo de identificacion de personas como REST API

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#10]
Utilizar cualquier tecnologia para poder lograr una identificacion de personas mediante reconocimiento facial y exponerlo como un servicio rest.

**Comment by RodrigoAGM** [comment]
El modelo de reconocimiento e identificación facial ya fue implementado. Pueden revisar el repo aquí: https://github.com/vot4me/blockchain_voting. 

Se plantea realizar una aplicación de escritorio en la cual se acceda primero al modulo de reconocimiento e identificación y, a partir de eso, se acceda al servicio de votos desplegado.

**Comment by enzoftware** [comment]
👍
