### ISSUE TITLE
Actualizar coleccion de postman 

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#13]
Actualizar coleccion de postman cuando se cambie el router

**Comment by Daztery** [comment]
¿Te refieres por los nuevos apis y el cambio de modelo de vote o a qué te refieres? @enzoftware

**Comment by enzoftware** [comment]
Actualizar el postman con los cambios de endpoint
 `/bet` -> `/vote`

Cosas asi

**Comment by enzoftware** [comment]
Lo cerre de casualidad xd

**Comment by enzoftware** [comment]
@Daztery lo haras tu?

**Comment by Daztery** [comment]
> @Daztery lo haras tu?

Sí

**Comment by enzoftware** [comment]
Avanza ps

**Comment by enzoftware** [comment]
Lo hara @Daztery

**Comment by Daztery** [comment]
#17 Se actualizó la coleccion, falta aprobar el pull request.
