### ISSUE TITLE
Blockchain architecture docs

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#5]
Documentacion acerca de la arquitecura de la solucion basada en blockchain

**Comment by enzoftware** [comment]
@MiguelDelgado27  Diagrama de secuencia

@Daztery Diagrama de arquitectura

**Comment by MiguelDelgado27** [comment]
Diagram done
![Sequence Diagram](https://user-images.githubusercontent.com/39664754/69117701-a46c8380-0a5e-11ea-9ff4-46aed98fa1d3.png)
