### ISSUE TITLE
Definir arquitectura del proyecto

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#6]
P2P or Network

**Comment by enzoftware** [comment]
https://medium.com/@mycoralhealth/code-a-simple-p2p-blockchain-in-go-46662601f417

**Comment by enzoftware** [comment]
https://github.com/morris-ribs/BlockchainBetSportGolang

**Comment by RodrigoAGM** [comment]
Network

**Comment by enzoftware** [comment]
@Daztery @MiguelDelgado27 ???

**Comment by MiguelDelgado27** [comment]
Network works!

**Comment by enzoftware** [comment]
Democracy, Network 🥇
