### ISSUE TITLE
Artefactos para la solucion

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#7]

**Comment by Daztery** [comment]
[Requerimientos.docx](https://github.com/vot4me/blockchain_voting/files/3781564/Requerimientos.docx)
![Diagrama de actividades](https://user-images.githubusercontent.com/26316409/67735190-60431180-f9d1-11e9-8223-72a77e4c50bc.jpeg)

**Comment by enzoftware** [comment]
Excelente 💯.

Esperando aprobacion de @RodrigoAGM

**Comment by RodrigoAGM** [comment]
Falta diagrama de despliegue del sistema completo

**Comment by enzoftware** [comment]
- [x]  Historias de usuario
- [x]  Diagrama de activiadades
- [ ]   Diagrama de despliegue

**Comment by MiguelDelgado27** [comment]
[Requerimientos.v2.docx](https://github.com/vot4me/blockchain_voting/files/3781812/Requerimientos.v2.docx)
![Diagramas](https://user-images.githubusercontent.com/39664754/67739525-c1261600-f9e0-11e9-96cc-02547cfaac1c.png)

**Comment by enzoftware** [comment]
Done
