### ISSUE TITLE
Define condiciones de correctitud para la aplicacion 

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#8]

**Comment by enzoftware** [comment]
[Definiciones de correctitud](https://docs.google.com/document/d/1vcQJa8Rh6pqlH3BzTdTIJ1XObKuZ-E5G9gBYSMAl3PE/edit?usp=sharing)


  | Bajo | Intermedio | Completo
-- | -- | -- | --
Como usuario quiero poder ingresar al sistema de votación con reconocimiento facial para realizar mi voto | El sistema no reconoce el rostro del votante de manera adecuada. | El sistema reconoce el rostro del votante de manera adecuada, sin embargo en ocasiones este es relacionado con la información de otro ciudadano. | El sistema de reconocimiento reconoce adecuadamente el rostro del usuario y lo relaciona con su información para realizar el voto.
Como usuario quiero poder enviar mi voto sin intermediarios para realizar mi voto de manera segura y libre de fraudes | El sistema muestra un error al enviar el voto o muestra la transacción completada sin enviar el voto correctamente | El sistema envía el voto pero no se refleja en el resto de los usuarios en menos de 1 minuto. | El sistema envía el voto pero y se refleja en el resto de los usuarios en menos de 1 minuto.

**Comment by enzoftware** [comment]
@Daztery y @MiguelDelgado27 opinen 🤔

**Comment by RodrigoAGM** [comment]
Done

**Comment by enzoftware** [comment]
@Daztery y @MiguelDelgado27 , esperando confirmacion para cerrar el issue

**Comment by MiguelDelgado27** [comment]
Correcto
