### ISSUE TITLE
Actualizar modelo de Block

### ISSUE THREAD

**Issue by enzoftware** [vot4me/blockchain_voting#9]
Convertir Bet en Vote
Revisar la rama `bet_blockchain_example`

**Comment by enzoftware** [comment]
Actualizar el modelo de bet a vote.

Incluyendo los controller, routers, model y blockchain

**Comment by MiguelDelgado27** [comment]
#14

**Comment by Daztery** [comment]
¿Acá pedías que se cambiara el modelo no? @enzoftware

**Comment by enzoftware** [comment]
Sip, el issue parece estar resuelto en #14, revisalo y apruebalo porfa

**Comment by enzoftware** [comment]
Solved! 💯
